/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SkillsList = {
  _type: "skillsList";
  skills?: Array<string>;
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type ProjectSpotlight = {
  _type: "projectSpotlight";
  projectHighlights?: Array<{
    _key: string;
  } & ProjectReference>;
};

export type TestimonialReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "testimonial";
};

export type TestimonialSlider = {
  _type: "testimonialSlider";
  testimonials?: Array<{
    _key: string;
  } & TestimonialReference>;
};

export type JobReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "job";
};

export type Resume = {
  _type: "resume";
  experiences?: Array<{
    _key: string;
  } & JobReference>;
};

export type AboutMe = {
  _type: "aboutMe";
  sectionTitle?: string;
  aboutContent?: RichText;
  aboutStats?: Array<{
    title?: string;
    value?: string;
    valuePrefix?: string;
    valueSuffix?: string;
    _key: string;
  }>;
  openToWork?: boolean;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Hero = {
  _type: "hero";
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  title?: string;
  subheading?: string;
  content?: RichText;
};

export type Seo = {
  _type: "seo";
  slug?: Slug;
  metaTitle?: string;
  metaDescription?: RichText;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Sections = Array<{
  _key: string;
} & Hero | {
  _key: string;
} & AboutMe | {
  _key: string;
} & Resume | {
  _key: string;
} & TestimonialSlider | {
  _key: string;
} & ProjectSpotlight | {
  _key: string;
} & SkillsList>;

export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    blank?: boolean;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
};

export type RichImage = {
  _type: "richImage";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  resumeLink?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  github?: string;
  linkedIn?: string;
};

export type Skills = {
  _id: string;
  _type: "skills";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  skill?: string;
  name?: string;
  skills?: Array<string>;
};

export type ProjectTypeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "projectType";
};

export type TagReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  title?: string;
  client?: string;
  clientLogo?: RichImage;
  description?: string;
  stats?: Array<{
    label?: string;
    value?: string;
    _type: "projectStat";
    _key: string;
  }>;
  techStack?: string;
  projectImage?: RichImage;
  projectLink?: string;
  agencyLink?: string;
  launchDate?: string;
  customColor?: "default" | "red" | "blue" | "green" | "purple";
  type?: ProjectTypeReference;
  tags?: Array<{
    _key: string;
  } & TagReference>;
};

export type ProjectType = {
  _id: string;
  _type: "projectType";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  company?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  quote?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  publishDate?: string;
};

export type Job = {
  _id: string;
  _type: "job";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  position?: string;
  company?: string;
  currentPosition?: boolean;
  startDate?: string;
  endDate?: string;
  note?: string;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  title?: string;
  sections?: Sections;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = SkillsList | ProjectReference | ProjectSpotlight | TestimonialReference | TestimonialSlider | JobReference | Resume | AboutMe | SanityImageAssetReference | Hero | Seo | Sections | RichText | Tag | RichImage | SanityFileAssetReference | SiteSettings | Skills | ProjectTypeReference | TagReference | Project | ProjectType | SanityImageCrop | SanityImageHotspot | Testimonial | Job | HomePage | Slug | MediaTag | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../frontend/src/lib/sanity/queries/documents/job.queries.ts
// Variable: allJobQuery
// Query: *[_type == "job"] | order(startDate desc)
export type AllJobQueryResult = Array<{
  _id: string;
  _type: "job";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  position?: string;
  company?: string;
  currentPosition?: boolean;
  startDate?: string;
  endDate?: string;
  note?: string;
}>;

// Source: ../frontend/src/lib/sanity/queries/documents/projects.queries.ts
// Variable: allProjectsQuery
// Query: *[_type == "project"]
export type AllProjectsQueryResult = Array<{
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  title?: string;
  client?: string;
  clientLogo?: RichImage;
  description?: string;
  stats?: Array<{
    label?: string;
    value?: string;
    _type: "projectStat";
    _key: string;
  }>;
  techStack?: string;
  projectImage?: RichImage;
  projectLink?: string;
  agencyLink?: string;
  launchDate?: string;
  customColor?: "blue" | "default" | "green" | "purple" | "red";
  type?: ProjectTypeReference;
  tags?: Array<{
    _key: string;
  } & TagReference>;
}>;

// Source: ../frontend/src/lib/sanity/queries/documents/testimonial.queries.ts
// Variable: allTestimonialsQuery
// Query: *[_type == "testimonial"]
export type AllTestimonialsQueryResult = Array<{
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  company?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  quote?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  publishDate?: string;
}>;

// Source: ../frontend/src/lib/sanity/queries/fragments.ts
// Variable: imageFragment
// Query: asset-> {		_id,		mimeType,		metadata {			dimensions		},		originalFilename,		url,	}
export type ImageFragmentResult = never;

// Source: ../frontend/src/lib/sanity/queries/fragments.ts
// Variable: fileFragment
// Query: asset -> {		_id,		assetId,		originalFilename,		url,	}
export type FileFragmentResult = never;

// Source: ../frontend/src/lib/sanity/queries/fragments.ts
// Variable: seoFragment
// Query: seo {		"slug": slug.current,		metaTitle,		metaDescription[] {				...,	...select(			_type == "richImage" => {		_type,		alt,		image {				asset-> {		_id,		mimeType,		metadata {			dimensions		},		originalFilename,		url,	}		}	}	)		},		ogImage {				asset-> {		_id,		mimeType,		metadata {			dimensions		},		originalFilename,		url,	}		},	}
export type SeoFragmentResult = never;

// Source: ../frontend/src/lib/sanity/queries/siteSettings.queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0] {	...,	"resumeLink": resumeLink {		asset-> {			_id,			url,		}	}}
export type SiteSettingsQueryResult = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  resumeLink: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
  } | null;
  github?: string;
  linkedIn?: string;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"job\"] | order(startDate desc)": AllJobQueryResult;
    "*[_type == \"project\"]": AllProjectsQueryResult;
    "*[_type == \"testimonial\"]": AllTestimonialsQueryResult;
    "\n\tasset-> {\n\t\t_id,\n\t\tmimeType,\n\t\tmetadata {\n\t\t\tdimensions\n\t\t},\n\t\toriginalFilename,\n\t\turl,\n\t}\n": ImageFragmentResult;
    "\n\tasset -> {\n\t\t_id,\n\t\tassetId,\n\t\toriginalFilename,\n\t\turl,\n\t}\n": FileFragmentResult;
    "\n\tseo {\n\t\t\"slug\": slug.current,\n\t\tmetaTitle,\n\t\tmetaDescription[] {\n\t\t\t\n\t...,\n\t...select(\n\t\t\n\t_type == \"richImage\" => {\n\t\t_type,\n\t\talt,\n\t\timage {\n\t\t\t\n\tasset-> {\n\t\t_id,\n\t\tmimeType,\n\t\tmetadata {\n\t\t\tdimensions\n\t\t},\n\t\toriginalFilename,\n\t\turl,\n\t}\n\n\t\t}\n\t}\n\n\t)\n\n\t\t},\n\t\togImage {\n\t\t\t\n\tasset-> {\n\t\t_id,\n\t\tmimeType,\n\t\tmetadata {\n\t\t\tdimensions\n\t\t},\n\t\toriginalFilename,\n\t\turl,\n\t}\n\n\t\t},\n\t}\n": SeoFragmentResult;
    "*[_type == \"siteSettings\"][0] {\n\t...,\n\t\"resumeLink\": resumeLink {\n\t\tasset-> {\n\t\t\t_id,\n\t\t\turl,\n\t\t}\n\t}\n}\n": SiteSettingsQueryResult;
  }
}

